# Generated by Django 3.1.3 on 2020-12-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_category_favourite'),
        ('users', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite',
            field=models.ManyToManyField(to='mainapp.Category'),
        ),
    ]
