# Generated by Django 3.1.3 on 2020-12-05 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20201204_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(related_name='article', to=settings.AUTH_USER_MODEL),
        ),
    ]
