# Generated by Django 3.1.3 on 2020-12-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_news_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='like',
            new_name='likes',
        ),
    ]
