# Generated by Django 3.1.3 on 2020-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_category_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='favourite',
        ),
    ]
