# Generated by Django 3.1.3 on 2020-12-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20201209_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
